In [1]:
import numpy as np #imports the numpy module

#### Creating Arrays

Arrays are used to store multiple values in one single variable.

Create a list and convert to a numpy array

In [2]:
mylist = [1,2,3]
x=np.array(mylist)
x

array([1, 2, 3])

Or just pass in a list directly

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

Pass in a list of lists to create a multidimensional array.

In [4]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

use the shape method to find the dimensions of the array. (rows,columns)

In [6]:
m.shape

(2, 3)

arange returns evenly spaced values within a given interval.

In [8]:
n = np.arange(0,30,2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

reshape returns an array with the same data with a new shape.

In [10]:
n = n.reshape(3,5) #reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [2]:
##r.reshape(36)[::7] #pulls every 7th number

linspace returns evenly spaced numbers over a specific interval.

In [11]:
o = np.linspace(0,4,9) #returns 9 evenly spaced values from 0 to 4
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

resize changes the shape and size of array in place

In [12]:
o.resize(3,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

ones returns a new array of given shape and type, filled with ones

In [13]:
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

ones: The shape is an int or tuple of ints to define the size of the array. If we just specify an int variable, a one-dimensional array will be returned. For a tuple of ints, the array of given shape will be returned.
The dtype is an optional parameter with default value as a float. It’s used to specify the data type of the array, for example, int.
The order defines the whether to store multi-dimensional array in row-major (C-style) or column-major (Fortran-style) order in memory.

zeros returns a new array of a given shape and type, filled with zeros

In [14]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

eye reutrns a 2D array with ones on the diagonal and zeros elsewhere.

In [15]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

diag extracts a diagonal or constructs a diagonal array.

In [17]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Create an array using repeating list (or see np.tile)

In [18]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

The numpy.tile() function constructs an array by repeating the parameter ‘A’  the number of times as specified by the ‘reps’ parameter.numpy.tile(A, reps)

In [22]:
A = np.array([1,2,3])
np.tile(A,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Repeat elements of an array using repeat.

In [24]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [25]:
np.repeat([1, 2, 3], 3)*3

array([3, 3, 3, 6, 6, 6, 9, 9, 9])


##### Combining Arrays

In [26]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

Use vstack to stack arrays in sequence vertically (row wise)

In [28]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Use hstack to stack arrays in sequence horizontally (column wise).

In [29]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])