### Operations

In [3]:
import numpy as np

In [4]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [5]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Use +, -, *, / and ** to perform element wise addition, subtraction, multiplication, division and power.

In [6]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [7]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [8]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [9]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


Let's look at transposing arrays. Transposing permutes the dimensions of the array. (swap rows and columns)

In [10]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

The shape of array z is (2,3) before transposing.

Use .T to get the transpose.

In [11]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

The number of rows has swapped with the number of columns.

In [12]:
z.T.shape

(3, 2)

Use .dtype to see the data type of the elements in the array.

In [13]:
z.dtype

dtype('int32')

Use .astype to cast to a specific type.
Casting is when you convert a variable value from one type to another.

In [14]:
z = z.astype('f')
z.dtype

dtype('float32')

### Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [15]:
a = np.array([-4,-2,1,3,5])

In [16]:
a.sum()

3

In [17]:
a.max()

5

In [18]:
a.min()

-4

In [19]:
a.mean()

0.59999999999999998

In [20]:
a.std()

3.2619012860600183

In [21]:
np.median(a)

1.0

In [22]:
a.std()

3.2619012860600183

argmax and argmin return the index of the maximum and minimum values in the array.

In [23]:
a.argmax()

4

In [24]:
a.argmin()

0

#### Indexing/Slicing

In [25]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144], dtype=int32)

Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [26]:
s[0], s[4], s[-1]

(0, 16, 144)

Use : to indicate a range. arrau[start:stop]
leave start or stop empty will default to the beginning/end of the array

In [27]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

Use negatives to count from the back.

In [28]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

A second : can be used to indicate step-size. array[start:stop:stepsize]

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [29]:
s[-5::2]

array([ 64, 100, 144], dtype=int32)

Let's look at a multidimensional array.

In [31]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: array[row, column]

In [32]:
r[2,2]

14

And use: to select a range of rows or columns

In [34]:
r[3, 3:6]

array([21, 22, 23])

Here we are selecting all the rows up to (and not including) row 2, and all the columns up tp (an not concluding) the last column.

In [37]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

This a slice of the last row, and only every other element. 

In [38]:
r[-1, ::2]

array([30, 32, 34])

We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see np.where)

In [39]:
r[r > 30]

array([31, 32, 33, 34, 35])

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [40]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

#### Copying Data

Be careful with copying and modifying arrays in NumPy!
r2 is a slice of r

In [41]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [42]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

r has also been changed!

In [43]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

To avoid this, use r.copy to create a copy that will not affect the original array

In [44]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now when r_copy is modified, r will not be changed.

In [45]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


#### Iterating over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [46]:
test = np.random.randint(0, 10, (4,3))
test

array([[6, 6, 1],
       [9, 6, 2],
       [6, 1, 9],
       [7, 2, 2]])

Iterate by row:

In [47]:
for row in test:
    print(row)

[6 6 1]
[9 6 2]
[6 1 9]
[7 2 2]


Iterate by index:

In [49]:
for i in range(len(test)):
    print(test[i])

[6 6 1]
[9 6 2]
[6 1 9]
[7 2 2]


Iterate by row and index: 

In [50]:
for i, row in enumerate(test):
    print('row', i, 'is', row )

row 0 is [6 6 1]
row 1 is [9 6 2]
row 2 is [6 1 9]
row 3 is [7 2 2]


Use zip to iterate over multiple iterables.

In [57]:
test2 = test**2
test2

array([[36, 36,  1],
       [81, 36,  4],
       [36,  1, 81],
       [49,  4,  4]], dtype=int32)

In [58]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[6 6 1] + [36 36  1] = [42 42  2]
[9 6 2] + [81 36  4] = [90 42  6]
[6 1 9] + [36  1 81] = [42  2 90]
[7 2 2] + [49  4  4] = [56  6  6]
