Q1: Python is an example of an interpreted language.

Q2: Data Science is interdiscplinary.

Q3: Data visualization is not a part of data science. FALSE

Q4: Which bracketing style does Python use for tuples? ()

Q5: In Python, strings are considered Mutable, and can be changed. FALSE

Q6: What is the result of the following code: ['a', 'b', 'c'] + [1, 2, 3]

In [15]:
x = ['a','b', 'c','d']
y = [1,2,3]
x+y

['a', 'b', 'c', 'd', 1, 2, 3]

Q7: String Slicing is a way to make a substring of a string in Python.

Q8: When you create a lambda, what type is returned? E.g. type(lambda x: x+1) returns

In [16]:
type(lambda x:x+1)

function

Q9: The epoch refers to Jan 1, year 1970.

Q10: This code, [x**2 for x in range(10)] , is an example of a list comprehension.  List comprehensions are used for creating new lists from other iterables.
As list comprehensions return lists, they consist of brackets containing the expression, which is executed for each element along with the for loop to iterate over each element.

In [18]:
#Q11: 
import numpy as np
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Q11: Given a 6x6 NumPy array r, which of the following options would slice the shaded elements? (diagonal down the middle of 0,7,14,21,28,35)

In [20]:
r.reshape(36)[::7] #reshapes to 36 elements and chose every 7th one to be in list

array([ 0,  7, 14, 21, 28, 35])

Q12: Given a 6x6 NumPy array r, which of the following options would slice the shaded elements? so 14,15,20,21

In [22]:
r[2:4,2:4] #returns 2 and 3 from row and column

array([[14, 15],
       [20, 21]])